version: '3'
services:
  kafkaMM:
    image: mycompany/kafka
    container_name: kafka-mirror-maker
    command: "bin/kafka-mirror-maker.sh \
    --consumer.config config/kafka-proxied-mm_consumer.properties \
    --producer.config config/kafka-proxied-mm_producer.properties \
    --whitelist=\"kafka-replicated-topic-1\""
